#!/bin/bash

CTR_PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin"
CTR_PATH="$CTR_PATH:/usr/sbin:/usr/bin:/sbin:/bin"


CTR_HOME="$HOME"

ARGS=(-v "$PWD:/$CTR_HOME" "--workdir=$CTR_HOME" "--rm")
#ARGS=(-v "$PWD:/work" "--workdir=/work")
ARGS+=(-v "$HOME/.local:$CTR_HOME/.local" -v "$HOME/.cache:$CTR_HOME/.cache")
ARGS+=(-v "$HOME/.config/ansible/ansible.cfg:/etc/ansible/ansible.cfg")
ARGS+=(-v "$HOME/.ansible:$CTR_HOME/.ansible")
ARGS+=(-v "$HOME/.ssh:$HOME/.ssh")
ARGS+=('--security-opt' 'label=disable'' --userns=keep-id' '-t')
ARGS+=(-e PATH="$CTR_PATH:$CTR_HOME/.local/bin")
ARGS+=(-i)
ARGS+=(-e GCP_AUTH_KIND="$GCP_AUTH_KIND" -e GCP_SERVICE_ACCOUNT_FILE="$GCP_SERVICE_ACCOUNT_FILE")
ARGS+=(-v "$HOME/.kube:$CTR_HOME/.kube")
ARGS+=(-e K8S_AUTH_KUBECONFIG="$CTR_HOME/.kube/config")

# args for using containers, i.e., having contianers as a part of your inventory
#CTR_LIB="/usr/lib/x86_64-linux-gnu"
#ARGS+=(-v "$HOME/.config/containers:$HOME/.config/containers")
#ARGS+=(-v "/usr/bin/podman:/usr/bin/podman" -v "/usr/bin/conmon:/usr/bin/conmon")
#ARGS+=(-v "/usr/bin/runc:/usr/bin/runc" -v "/run/user/1000:/run/user/1000")
#ARGS+=(-v "/usr/lib64/libgpgme.so.11:$CTR_LIB/libgpgme.so.11" )
#ARGS+=(-v "/usr/lib64/libgpgme.so.11.21.0:$CTR_LIB/libgpgme.so.11.21.0" )
#ARGS+=('--net=host' '--privileged')

# really only mounting bc on one playbook i'm running
ARGS+=(-v "/home/jeff/ondemand:/home/jeff/ondemand")

# python:3 works just fine, unless you want to connect to containers
# from within this contianer (ends up getting cannot find mappings for user 
# 1000: No subuid ranges found for user \\"1000\\" in /etc/subuid")
#IMG="ansible:user"
IMG="python:3"

podman run ${ARGS[@]} "$IMG" $(basename "$0") "$@"
#podman run ${ARGS[@]} "$IMG" "$@"
