#!/bin/bash

PKG_CONFIG_PATH="/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"

ARGS=('--rm' '-v' "$HOME:$HOME" "--workdir=$PWD")
ARGS+=('--userns=keep-id' '--security-opt' 'label=disable')
ARGS+=(-e "PKG_CONFIG_PATH=$PKG_CONFIG_PATH")

ARGS+=(-v "/tmp:/tmp")

ARGS+=(-e "CXX_FLAGS=-no-pie" -e "CXXFLAGS=-no-pie" -e "CFLAGS=-no-pie")
ARGS+=(-e "EXTRA_CXXFLAGS=-no-pie")

#IMG="buildpack-deps:bullseye"
IMG="buildpack-deps:jeff"

podman run "${ARGS[@]}" "$IMG" $(basename "$0") "$@"
