#!/bin/bash

PKG_CONFIG_PATH="/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"

ARGS=('--rm' '-v' "$PWD:/src" "--workdir=/src")
ARGS+=('--userns=keep-id' '--security-opt' 'label=disable')
ARGS+=(-e "PKG_CONFIG_PATH=$PKG_CONFIG_PATH")


IMG="buildpack-deps:bullseye"

podman run "${ARGS[@]}" "$IMG" "$@"
