#!/bin/sh


if [ -z $1 ]; then
  echo 'you must specify $1 as [start/stop/restart]'
  exit 1
fi

CMD=$1

function stop_ctr(){
  CTR=$(podman ps | grep solargraph | awk '{print $1}')
  podman kill $CTR
}

function start_ctr(){
  RUBY_PORT=7658 solargraph socket --host=0.0.0.0 > /tmp/solargraph.out 2>&1 &
}

if [ "$CMD" == "start" ]; then
  start_ctr
elif [ "$CMD" == "stop" ]; then
  stop_ctr
elif [ "$CMD" == "restart" ]; then
  stop_ctr
  start_ctr
else
  echo "cmd '$CMD' not understood"
fi
