#!/bin/sh


if [ -z $1 ]; then
  echo 'you must specify $1 as [start/stop/restart]'
  exit 1
fi

CMD=$1

function stop_ctr(){
  podman kill solargraph
}

function start_ctr(){
  ARGS=("--rm")
  ARGS+=('--security-opt' 'label=disable'' --userns=keep-id')
  ARGS+=(-v "$HOME/.gem:$HOME/.gem")
  ARGS+=(-v "$HOME/.gem/ruby:/var/lib/gems/2.5.0")
  ARGS+=(-v "$HOME/src/misc/ctr-bin:/usr/local/bin")
  ARGS+=(-v "$HOME/.solargraph:$HOME/.solargraph")
  ARGS+=(-p "7658:7658" "--name=solargraph")

  EXE="/usr/local/bin/solargraph"
  CTR_CMD="$EXE socket --host=0.0.0.0"
  IMG="ood:test"

  podman run ${ARGS[@]} "$IMG" $CTR_CMD > /tmp/solargraph.out 2>&1 &
}

if [ "$CMD" == "start" ]; then
  start_ctr
elif [ "$CMD" == "stop" ]; then
  stop_ctr
elif [ "$CMD" == "restart" ]; then
  stop_ctr
  start_ctr
else
  echo "cmd '$CMD' not understood"
fi
